(() => {
  const $=s=>document.querySelector(s), canvas=$('#gameCanvas'), ctx=canvas.getContext('2d');
  const W=360,H=338; canvas.width=W;canvas.height=H;
  const screens={title:$('#titleScreen'),play:$('#playScreen'),result:$('#resultScreen')};
  const chars={mana:{name:'\u30de\u30ca',type:'bear',style:'SPIN',track:.62,spin:.075,power:1.02},maeda:{name:'\u30de\u30a8\u30c0',type:'gorilla',style:'SMASH',track:.73,spin:.012,power:1.32}};
  const levels={easy:{name:'\u30a4\u30fc\u30b8\u30fc',track:1,ball:.92,aim:54},normal:{name:'\u30ce\u30fc\u30de\u30eb',track:1.35,ball:1.08,aim:40},hard:{name:'\u30cf\u30fc\u30c9',track:1.72,ball:1.28,aim:29}};
  let rival,level='normal',g,raf,pointerId,audio;
  function show(n){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[n].classList.add('active')}
  function beep(f,d=.08,type='sine'){try{audio??=new AudioContext();const o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.06,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){}}
  function begin(key){rival=chars[key];const d=levels[level];$('#enemyName').textContent=rival.name;$('#enemyMini').className='mini '+rival.type;$('#levelName').textContent=d.name;$('#styleName').textContent=rival.style;g={px:180,ex:180,bx:180,by:169,vx:2.15,vy:2.65,ps:0,es:0,rally:0,last:performance.now(),pause:850,locked:false,ended:false,face:'neutral',enemyFace:'neutral',faceUntil:0,skill:null,skillUntil:0,skillCD:0,track:rival.track*d.track,ball:d.ball,aim:d.aim};$('#playerScore').textContent='0';$('#enemyScore').textContent='0';$('#rally').textContent='0';show('play');cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}
  function activeMood(v){return performance.now()<g.faceUntil?v:'neutral'}
  function face(x,y,type,mood,s=.72){ctx.save();ctx.translate(x,y);ctx.scale(s,s);const gorilla=type==='gorilla',bear=type==='bear';ctx.strokeStyle='#513b50';ctx.lineWidth=3;
    if(gorilla){ctx.fillStyle='#20272b';ctx.beginPath();ctx.ellipse(0,9,33,31,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#303a3f';ctx.beginPath();ctx.ellipse(-27,15,14,18,.35,0,7);ctx.ellipse(27,15,14,18,-.35,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#080b0d';ctx.beginPath();ctx.ellipse(-13,-7,13,5,-.2,0,7);ctx.ellipse(13,-7,13,5,.2,0,7);ctx.fill()}else{ctx.fillStyle=bear?'#b98a65':'#efe8ee';ctx.beginPath();ctx.arc(0,0,24,0,7);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(-16,-17,bear?9:6,0,7);ctx.arc(16,-17,bear?9:6,0,7);ctx.fill();ctx.stroke();if(!bear){ctx.beginPath();ctx.ellipse(-10,-28,6,16,-.2,0,7);ctx.ellipse(10,-28,6,16,.2,0,7);ctx.fill();ctx.stroke()}}
    ctx.fillStyle=gorilla?'#687277':bear?'#edbd95':'#fff';ctx.beginPath();ctx.ellipse(0,10,gorilla?20:14,gorilla?13:10,0,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#121719';if(mood==='upset'){ctx.fillRect(-13,-4,10,3);ctx.fillRect(3,-4,10,3)}else{ctx.beginPath();ctx.arc(-8,-2,3,0,7);ctx.arc(8,-2,3,0,7);ctx.fill()}ctx.strokeStyle='#263033';ctx.beginPath();if(mood==='upset')ctx.arc(0,18,7,3.14,0);else ctx.arc(0,11,mood==='joy'?8:5,0,3.14);ctx.stroke();if(mood==='joy'){ctx.fillStyle='#f69db2';ctx.beginPath();ctx.arc(-17,10,4,0,7);ctx.arc(17,10,4,0,7);ctx.fill()}ctx.restore()}
  function render(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#bce4d7';ctx.fillRect(0,0,W,H);ctx.fillStyle='#9dcebf';ctx.fillRect(0,H/2-4,W,8);ctx.fillStyle='rgba(255,255,255,.72)';for(let x=5;x<W;x+=17)ctx.fillRect(x,H/2-1,9,2);face(g.ex,40,rival.type,activeMood(g.enemyFace));face(g.px,H-39,'rabbit',activeMood(g.face));ctx.fillStyle='#fff';ctx.fillRect(g.ex-31,70,62,7);ctx.fillStyle='#ff76aa';ctx.fillRect(g.px-33,H-77,66,8);ctx.fillStyle=g.skill==='spin'?'#b9efff':'#fff7d1';ctx.beginPath();ctx.arc(g.bx,g.by,7,0,7);ctx.fill();ctx.strokeStyle='#e4a45a';ctx.stroke()}
  function serve(toPlayer){g.pause=760;g.locked=true;g.bx=180;g.by=169;g.vx=(Math.random()>.5?1:-1)*2.12;g.vy=toPlayer?2.65:-2.65;setTimeout(()=>{if(!g.ended)g.locked=false},770)}
  function point(player){if(g.locked||g.ended)return;g.locked=true;if(player){g.ps++;g.face='joy';g.enemyFace='upset';flash('POINT!');beep(700,.13)}else{g.es++;g.face='upset';g.enemyFace='joy';flash('OH NO!');beep(160,.18,'sawtooth')}g.faceUntil=performance.now()+1200;$('#playerScore').textContent=g.ps;$('#enemyScore').textContent=g.es;g.rally=0;$('#rally').textContent=0;const win=g.ps>=11&&g.ps-g.es>=2,lose=g.es>=11&&g.es-g.ps>=2;if(win||lose){g.ended=true;setTimeout(()=>finish(win),650);return}if(g.ps>=10&&g.es>=10)flash('DEUCE!');serve(player)}
  function flash(t){const e=$('#gameMessage');e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
  function finish(win){cancelAnimationFrame(raf);show('result');$('#resultKicker').textContent=win?'PERFECT RALLY!':'NEXT TIME!';$('#resultTitle').textContent=win?'YOU WIN!':'GAME OVER';$('#resultText').textContent=win?`${rival.name}との勝負に勝ったよ！`:`${rival.name}はなかなか手ごわい…！`;const f=$('#resultFace');f.className='portrait rabbit '+(win?'happy win':'sad');beep(win?880:150,.3,win?'triangle':'sawtooth')}
  function hitPlayer(){let mult=1.04,curve=.02;if(g.skill==='smash'){mult=1.58;curve=.005;flash('SMASH!');beep(860,.1,'square')}if(g.skill==='spin'){mult=1.08;curve=.105;flash('SPIN!');beep(560,.1)}g.vy=-Math.abs(g.vy)*mult;g.vx+=(g.bx-g.px)*curve;g.skill=null;g.rally++;$('#rally').textContent=g.rally}
  function hitEnemy(){g.vy=Math.abs(g.vy)*rival.power;g.vx+=(g.bx-g.ex)*rival.spin;g.rally++;$('#rally').textContent=g.rally;beep(rival.type==='gorilla'?330:500,.06)}
  function frame(t){const dt=Math.min(2,(t-g.last)/16.67);g.last=t;if(g.pause>0){g.pause-=dt*16.67;render();raf=requestAnimationFrame(frame);return}g.ex+=Math.sign(g.bx-g.ex)*Math.min(Math.abs(g.bx-g.ex),g.track*1.7*dt);g.bx+=g.vx*g.ball*dt;g.by+=g.vy*g.ball*dt;if(g.bx<7||g.bx>W-7){g.vx*=-1;g.bx=Math.max(7,Math.min(W-7,g.bx))}if(g.vy<0&&g.by<77){if(Math.abs(g.bx-g.ex)<g.aim)hitEnemy();else point(true)}if(g.vy>0&&g.by>H-78){if(Math.abs(g.bx-g.px)<43)hitPlayer();else point(false)}if(performance.now()>g.skillUntil)g.skill=null;render();raf=requestAnimationFrame(frame)}
  function setPlayer(e){const r=canvas.getBoundingClientRect();g.px=Math.max(35,Math.min(W-35,(e.clientX-r.left)*W/r.width))}function use(skill){if(!g||g.ended||performance.now()<g.skillCD)return;g.skill=skill;g.skillUntil=performance.now()+850;g.skillCD=performance.now()+1200;flash(skill==='spin'?'SPIN READY':'SMASH READY')}
  canvas.addEventListener('pointerdown',e=>{pointerId=e.pointerId;canvas.setPointerCapture(pointerId);setPlayer(e)});canvas.addEventListener('pointermove',e=>{if(e.pointerId===pointerId)setPlayer(e)});canvas.addEventListener('pointerup',()=>pointerId=null);$('#spinButton').onclick=()=>use('spin');$('#smashButton').onclick=()=>use('smash');document.querySelectorAll('.difficulty button').forEach(b=>b.onclick=()=>{level=b.dataset.level;document.querySelectorAll('.difficulty button').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('.enemy-card').forEach(b=>b.onclick=()=>begin(b.dataset.enemy));$('#retryButton').onclick=()=>begin(rival.type==='bear'?'mana':'maeda');$('#titleButton').onclick=()=>show('title');$('#backButton').onclick=()=>{cancelAnimationFrame(raf);show('title')};
})();
