(() => {
  const $ = s => document.querySelector(s), canvas = $('#gameCanvas'), ctx = canvas.getContext('2d');
  const screens={title:$('#titleScreen'),play:$('#playScreen'),result:$('#resultScreen')};
  const config={mana:{name:'マナ',type:'bear',style:'スピン重視',ai:.78,spin:.06,power:1.01},maeda:{name:'マエダ',type:'gorilla',style:'パワー重視',ai:.87,spin:.012,power:1.18}};
  const levels={easy:{name:'イージー',ai:.76,speed:.92},normal:{name:'ノーマル',ai:1,speed:1},hard:{name:'ハード',ai:1.23,speed:1.1}};
  const W=360,H=338; canvas.width=W;canvas.height=H; let opponent,level='normal',state,raf,audioCtx,pointerId;
  function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
  function sound(freq,d=.08,type='sine'){try{audioCtx??=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.07,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(e){}}
  function start(key){opponent=config[key];const lv=levels[level];$('#enemyName').textContent=opponent.name;$('#enemyMini').className='mini '+opponent.type;$('#levelName').textContent=lv.name;$('#styleName').textContent=opponent.style;state={px:W/2,ex:W/2,bx:W/2,by:H*.53,vx:(Math.random()>.5?1:-1)*2.2,vy:2.65,ps:0,es:0,rally:0,last:performance.now(),face:'neutral',enemyFace:'neutral',faceUntil:0,pause:800,ai:opponent.ai*lv.ai,speed:lv.speed};$('#playerScore').textContent='0';$('#enemyScore').textContent='0';$('#rally').textContent='0';show('play');cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
  function mood(current){return performance.now()<state.faceUntil?current:'neutral'}
  function drawFace(x,y,kind,expression,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const gorilla=kind==='gorilla';const base=gorilla?'#63506f':kind==='bear'?'#b98a65':'#efe8ee';const muzzle=gorilla?'#a98cb7':kind==='bear'?'#ebbd94':'#fff9fa';ctx.strokeStyle='#50394e';ctx.lineWidth=3;ctx.fillStyle=base;
    if(gorilla){ctx.beginPath();ctx.ellipse(0,8,30,32,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#50394e';ctx.beginPath();ctx.ellipse(-14,-8,11,5,-.25,0,Math.PI*2);ctx.ellipse(14,-8,11,5,.25,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=base;ctx.beginPath();ctx.arc(-16,-17,9,0,Math.PI*2);ctx.arc(16,-17,9,0,Math.PI*2);ctx.fill();ctx.stroke();if(kind==='rabbit'){ctx.beginPath();ctx.ellipse(-10,-27,6,16,-.2,0,Math.PI*2);ctx.ellipse(10,-27,6,16,.2,0,Math.PI*2);ctx.fill();ctx.stroke()}}
    ctx.fillStyle=muzzle;ctx.beginPath();ctx.ellipse(0,10,gorilla?19:14,gorilla?13:10,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#35283a';
    if(expression==='upset'){ctx.fillRect(-12,-4,9,3);ctx.fillRect(3,-4,9,3)}else if(expression==='joy'){ctx.beginPath();ctx.arc(-8,-2,3,0,Math.PI*2);ctx.arc(8,-2,3,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.arc(-8,-2,2.5,0,Math.PI*2);ctx.arc(8,-2,2.5,0,Math.PI*2);ctx.fill()}
    ctx.strokeStyle='#50394e';ctx.lineWidth=2.5;ctx.beginPath();if(expression==='upset')ctx.arc(0,17,7,Math.PI,0);else if(expression==='joy'){ctx.arc(0,11,8,0,Math.PI);ctx.fillStyle='#ef7894';ctx.fill()}else ctx.arc(0,12,5,0,Math.PI);ctx.stroke();if(expression==='joy'){ctx.fillStyle='#f49aae';ctx.beginPath();ctx.arc(-17,10,4,0,Math.PI*2);ctx.arc(17,10,4,0,Math.PI*2);ctx.fill()}ctx.restore()}
  function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#bce4d7';ctx.fillRect(0,0,W,H);ctx.fillStyle='#9dcebf';ctx.fillRect(0,H/2-4,W,8);ctx.fillStyle='rgba(255,255,255,.72)';for(let x=5;x<W;x+=17)ctx.fillRect(x,H/2-1,9,2);drawFace(state.ex,39,opponent.type,mood(state.enemyFace),.72);drawFace(state.px,H-38,'rabbit',mood(state.face),.72);ctx.fillStyle='#fff';ctx.fillRect(state.ex-31,70,62,7);ctx.fillStyle='#ff76aa';ctx.fillRect(state.px-33,H-77,66,8);ctx.beginPath();ctx.fillStyle='#fff7d1';ctx.arc(state.bx,state.by,7,0,7);ctx.fill();ctx.strokeStyle='#e4a45a';ctx.lineWidth=1;ctx.stroke()}
  function serve(toPlayer){state.pause=800;state.bx=W/2;state.by=H*.53;state.vx=(Math.random()>.5?1:-1)*2.15;state.vy=toPlayer?2.65:-2.65}
  function score(player){if(player){state.ps++;state.face='joy';state.enemyFace='upset';sound(660,.14);flash('POINT!')}else{state.es++;state.face='upset';state.enemyFace='joy';sound(180,.2,'sawtooth');flash('OH NO…')}state.faceUntil=performance.now()+1100;$('#playerScore').textContent=state.ps;$('#enemyScore').textContent=state.es;state.rally=0;$('#rally').textContent=0;const won=state.ps>=11&&state.ps-state.es>=2,lost=state.es>=11&&state.es-state.ps>=2;if(won||lost){setTimeout(()=>finish(won),600);return}if(state.ps>=10&&state.es>=10)flash('DEUCE!');serve(player)}
  function flash(text){const e=$('#gameMessage');e.textContent=text;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
  function finish(win){cancelAnimationFrame(raf);show('result');$('#resultKicker').textContent=win?'PERFECT RALLY!':'NEXT TIME!';$('#resultTitle').textContent=win?'YOU WIN!':'GAME OVER';$('#resultText').textContent=win?`${opponent.name}との勝負に勝ったよ！`:`${opponent.name}はなかなか手ごわい…！`;$('#resultFace').className='portrait rabbit '+(win?'happy win':'sad');sound(win?880:160,.35,win?'triangle':'sawtooth')}
  function loop(t){const dt=Math.min(2,(t-state.last)/16.67);state.last=t;if(state.pause>0){state.pause-=dt*16.67;draw();raf=requestAnimationFrame(loop);return}state.ex+=Math.sign(state.bx-state.ex)*Math.min(Math.abs(state.bx-state.ex),state.ai*1.5*dt);state.bx+=state.vx*state.speed*dt;state.by+=state.vy*state.speed*dt;if(state.bx<7||state.bx>W-7){state.vx*=-1;state.bx=Math.max(7,Math.min(W-7,state.bx));sound(350,.04)}if(state.vy<0&&state.by<77){if(Math.abs(state.bx-state.ex)<39){state.vy=Math.abs(state.vy)*opponent.power;state.vx+=(state.bx-state.ex)*opponent.spin;sound(opponent.type==='gorilla'?380:510,.06);state.rally++;$('#rally').textContent=state.rally}else score(true)}if(state.vy>0&&state.by>H-78){if(Math.abs(state.bx-state.px)<43){state.vy=-Math.abs(state.vy)*1.03;state.vx+=(state.bx-state.px)*.019;sound(590,.05);state.rally++;$('#rally').textContent=state.rally}else score(false)}draw();raf=requestAnimationFrame(loop)}
  function setP(e){const r=canvas.getBoundingClientRect();state.px=Math.max(35,Math.min(W-35,(e.clientX-r.left)*W/r.width))}canvas.addEventListener('pointerdown',e=>{pointerId=e.pointerId;canvas.setPointerCapture(pointerId);setP(e)});canvas.addEventListener('pointermove',e=>{if(e.pointerId===pointerId)setP(e)});canvas.addEventListener('pointerup',()=>pointerId=null);document.querySelectorAll('.difficulty button').forEach(b=>b.onclick=()=>{level=b.dataset.level;document.querySelectorAll('.difficulty button').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('.enemy-card').forEach(b=>b.onclick=()=>start(b.dataset.enemy));$('#retryButton').onclick=()=>start(opponent.type==='bear'?'mana':'maeda');$('#titleButton').onclick=()=>show('title');$('#backButton').onclick=()=>{cancelAnimationFrame(raf);show('title')};
})();
