(() => {
  const $ = s => document.querySelector(s);
  const canvas = $('#gameCanvas'), ctx = canvas.getContext('2d');
  const screens = { title: $('#titleScreen'), play: $('#playScreen'), result: $('#resultScreen') };
  const cfg = { mana: { name:'マナ', color:'#b98a65', accent:'#e7bb92', speed:.78, type:'bear' }, maeda: { name:'マエダ', color:'#7e6291', accent:'#ae91bf', speed:.94, type:'gorilla' } };
  let opponent, state, raf, audioCtx;
  const W=360,H=338;
  canvas.width=W; canvas.height=H;
  function show(name){ Object.values(screens).forEach(x=>x.classList.remove('active')); screens[name].classList.add('active'); }
  function sound(freq,d=.08,type='sine'){ try { audioCtx ??= new AudioContext(); const o=audioCtx.createOscillator(), g=audioCtx.createGain(); o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.07,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d); }catch(e){} }
  function start(key){ opponent=cfg[key]; $('#enemyName').textContent=opponent.name; $('#enemyMini').className='mini '+opponent.type; state={px:W/2,ex:W/2,bx:W/2,by:H*.53,vx:(Math.random()>.5?1:-1)*2.25,vy:2.7,ps:0,es:0,rally:0,last:performance.now(),face:'happy', enemyFace:'happy', pause:700}; $('#playerScore').textContent='0';$('#enemyScore').textContent='0';$('#rally').textContent='0';show('play'); cancelAnimationFrame(raf); raf=requestAnimationFrame(loop); }
  function drawFace(x,y,kind,mood,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle=kind==='gorilla'?'#7e6291':'#b98a65';ctx.strokeStyle='#674658';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=kind==='gorilla'?'#ae91bf':'#e7bb92';ctx.beginPath();ctx.ellipse(0,9,15,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#392938';ctx.beginPath(); if(mood==='sad'){ctx.moveTo(-11,-2);ctx.lineTo(-5,-5);ctx.moveTo(5,-5);ctx.lineTo(11,-2)}else{ctx.arc(-8,-3,2,0,7);ctx.arc(8,-3,2,0,7)}ctx.fill();ctx.strokeStyle='#704756';ctx.lineWidth=2;ctx.beginPath();if(mood==='sad')ctx.arc(0,15,6,Math.PI,0);else ctx.arc(0,11,6,0,Math.PI);ctx.stroke();ctx.restore();}
  function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#bce4d7';ctx.fillRect(0,0,W,H);ctx.fillStyle='#9dcebf';ctx.fillRect(0,H/2-4,W,8);ctx.fillStyle='rgba(255,255,255,.72)';for(let x=5;x<W;x+=17)ctx.fillRect(x,H/2-1,9,2); drawFace(state.ex,39,opponent.type,state.enemyFace,.72);drawFace(state.px,H-38,'rabbit',state.face,.72);ctx.fillStyle='#fff';ctx.fillRect(state.ex-31,70,62,7);ctx.fillStyle='#ff76aa';ctx.fillRect(state.px-33,H-77,66,8);ctx.beginPath();ctx.fillStyle='#fff7d1';ctx.arc(state.bx,state.by,7,0,7);ctx.fill();ctx.strokeStyle='#e4a45a';ctx.lineWidth=1;ctx.stroke();}
  function score(player){ if(player){state.ps++;state.face='happy';state.enemyFace='sad'; sound(660,.14); flash('POINT!');}else{state.es++;state.face='sad';state.enemyFace='happy';sound(180,.2,'sawtooth');flash('OH NO…');} $('#playerScore').textContent=state.ps;$('#enemyScore').textContent=state.es;state.rally=0;$('#rally').textContent=0;if(state.ps>=7||state.es>=7){setTimeout(()=>finish(state.ps>=7),500);return;}state.pause=800;state.bx=W/2;state.by=H*.53;state.vx=(Math.random()>.5?1:-1)*2.2;state.vy=player?-2.7:2.7; }
  function flash(text){const el=$('#gameMessage');el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');}
  function finish(win){cancelAnimationFrame(raf);show('result');$('#resultKicker').textContent=win?'PERFECT RALLY!':'NEXT TIME!';$('#resultTitle').textContent=win?'YOU WIN!':'GAME OVER';$('#resultText').textContent=win?`${opponent.name}との勝負に勝ったよ！`:`${opponent.name}はなかなか手ごわい…！`;const f=$('#resultFace');f.className='portrait rabbit '+(win?'happy win':'sad');sound(win?880:160,.35,win?'triangle':'sawtooth');}
  function loop(t){const dt=Math.min(2,(t-state.last)/16.67);state.last=t;if(state.pause>0){state.pause-=dt*16.67;draw();raf=requestAnimationFrame(loop);return;}state.ex+=Math.sign(state.bx-state.ex)*Math.min(Math.abs(state.bx-state.ex),opponent.speed*1.5*dt);state.bx+=state.vx*dt;state.by+=state.vy*dt;if(state.bx<7||state.bx>W-7){state.vx*=-1;state.bx=Math.max(7,Math.min(W-7,state.bx));sound(350,.04);}if(state.vy<0&&state.by<77){if(Math.abs(state.bx-state.ex)<39){state.vy=Math.abs(state.vy)*1.045;state.vx+=(state.bx-state.ex)*.022;sound(490,.05);state.rally++;$('#rally').textContent=state.rally;}else score(true);}if(state.vy>0&&state.by>H-78){if(Math.abs(state.bx-state.px)<43){state.vy=-Math.abs(state.vy)*1.035;state.vx+=(state.bx-state.px)*.019;sound(590,.05);state.rally++;$('#rally').textContent=state.rally;}else score(false);}draw();raf=requestAnimationFrame(loop);}
  let pointerId;function setP(e){const r=canvas.getBoundingClientRect();state.px=Math.max(35,Math.min(W-35,(e.clientX-r.left)*W/r.width));}canvas.addEventListener('pointerdown',e=>{pointerId=e.pointerId;canvas.setPointerCapture(pointerId);setP(e);});canvas.addEventListener('pointermove',e=>{if(e.pointerId===pointerId)setP(e);});canvas.addEventListener('pointerup',()=>pointerId=null);document.querySelectorAll('.enemy-card').forEach(b=>b.addEventListener('click',()=>start(b.dataset.enemy)));$('#retryButton').onclick=()=>start(opponent.type==='bear'?'mana':'maeda');$('#titleButton').onclick=()=>show('title');$('#backButton').onclick=()=>{cancelAnimationFrame(raf);show('title');};
})();
